### ISSUE TITLE
Ability to mirror tasks between projects

### ISSUE THREAD

**Issue by fizyk** [ClearcodeHQ/jira_timemachine#2]
For the case where both jira should contain same issue grid (reference)

**Comment by mmaslowskicc** [comment]
These are some more complex issues here:

* should it create new issues in the destination Jira?
* should it assume equal issue numbers in both? (surely projects have different keys in different Jiras)

It would be nice to just use a specific mapping of issues, erroring on worklogs from unmapped issues. (It's idempotent, so we can retry it after updating such a mapping.)

**Comment by fizyk** [comment]
I think both approaches might be useful in long term
