### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/jira_timemachine#3]
There is error-prone logic responsible for copying and not duplicating worklogs, we can test it.

**Comment by fizyk** [comment]
are current tests sufficient? I'll have to split the code into modules first, maybe I'll be able to see more things to tests (?)

**Comment by mmaslowskicc** [comment]
`test_match_worklog` probably checks the original issue. We can add more later.

**Comment by fizyk** [comment]
Closing it for now then
